name: Preview

env:
  CARGO_TERM_COLOR: always

on:
  workflow_run:
    workflows: [Trigger]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'  
    steps:
      - name: Log
        uses: actions/github-script@v6
        with:
          script: |
            let prs = context.payload.workflow_run.pull_requests;
            console.log("Number of PRs: ", prs.length);
            console.log("First PR: ", prs[0]);
            for (let i in prs) {
               console.log("PR: ", i);
            }
