name: Preview

env:
  CARGO_TERM_COLOR: always

on:
  workflow_run:
    workflows: [Trigger]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'  
    steps:
      - name: Log
        uses: actions/github-script@v6
        id: log
        with:
          script: |
            let prs = context.payload.workflow_run.pull_requests;
            console.log("Number of PRs: ", prs.length);
            console.log("First PR: ", prs[0]);
            for (let i of prs) {
               console.log("PR: ", i);
            }
            core.setOutput("prnumber", prs[O].number);
      
      - name: Comment PR Number
        uses: Beakyn/gha-comment-pull-request@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          pull-request-number: steps.log.outputs.prnumber
          description-message: |
            ----
            Script PR Number: ${{ steps.log.outputs.prnumber }}
            Context PR Number: ${{ github.event.workflow_run.pull_requests[0].number }}
