name: Trigger Close

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  xtask:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "PR Number: ${{ github.event.number }}"'
